<?php

declare(strict_types=1);

/**
 * EasySQL API Client — auto-generated.
 *
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec.
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY — regeneration overwrites it.
 * Regenerate with: make generate (EASYSQL_API_URL defaults to https://api.easysql.net)
 */

namespace Clearsoft\EasySQL\Client;

use GuzzleHttp\Client as GuzzleClient;
use Psr\Http\Message\ResponseInterface;
use Clearsoft\EasySQL\Client\Exceptions\ApiException;
use Clearsoft\EasySQL\Client\Http\TokenManager;
use Clearsoft\EasySQL\Client\Http\TokenStoreInterface;

class Client
{
    private GuzzleClient $http;
    private ?TokenManager $tokens = null;

    public function __construct(array $config = [])
    {
        // Full HTTP client injection (tests, custom transports). Token helpers
        // become no-ops in this mode — the caller owns the client.
        if (isset($config['http_client']) && $config['http_client'] instanceof GuzzleClient) {
            $this->http = $config['http_client'];
            return;
        }

        $baseUrl = rtrim($config['base_url'] ?? 'https://api.easysql.net', '/');

        $this->tokens = new TokenManager(
            $baseUrl,
            $config['access_token'] ?? null,
            $config['refresh_token'] ?? null,
            $config['handler'] ?? null,
        );

        $this->http = new GuzzleClient([
            'handler'     => $this->tokens->buildStack(),
            'base_uri'    => $baseUrl,
            'timeout'     => $config['timeout'] ?? 30.0,
            'http_errors' => false,
            'headers'     => [
                'Accept'       => 'application/json',
                'Content-Type' => 'application/json',
            ],
        ]);
    }

    /**
     * Set the Bearer token for authenticated requests.
     *
     * The underlying HTTP client is not recreated — the token is applied by
     * the handler stack on the next request.
     */
    public function setAccessToken(string $token): void
    {
        $this->tokens?->setAccessToken($token);
    }

    /**
     * Register a token store. When set, the client refreshes the access token
     * automatically (once) on a 401 response and persists the new tokens.
     */
    public function setTokenStore(TokenStoreInterface $store): void
    {
        $this->tokens?->setTokenStore($store);
    }

    /**
     * Get the underlying Guzzle client for custom requests.
     */
    public function getHttpClient(): GuzzleClient
    {
        return $this->http;
    }

    // ── Internal request helper ───────────────────────────────

    private function request(string $method, string $path, array $options = []): ResponseInterface
    {
        $response = $this->http->request($method, $path, $options);
        $statusCode = $response->getStatusCode();
        if ($statusCode >= 400) {
            throw ApiException::fromResponse($response);
        }
        return $response;
    }

    // ── Generated API methods ────────────────────────────────

    /**
     * User's queries from Cloudflare Analytics Engine (last N days).
     * @param array $query
     * @return array
     */
    public function listAnalyticsQueries(array $query = []): array
    {
        $response = $this->request('get', '/v1/analytics/queries', [
            'query' => $query,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Create API key (returns full key once).
     * @param array $body
     * @return array
     */
    public function createApiKey(array $body): array
    {
        $response = $this->request('post', '/v1/api-keys', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Revoke API key (soft delete).
     * @param string $key_id
     * @return void
     */
    public function deleteApiKey(string $key_id): void
    {
        $response = $this->request('delete', '/v1/api-keys/' . $key_id);
    }

    /**
     * List API keys (without secret).
     * @return array
     */
    public function listApiKeys(): array
    {
        $response = $this->request('get', '/v1/api-keys');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete current user (hard delete).
     * @return void
     */
    public function deleteMe(): void
    {
        $response = $this->request('delete', '/v1/auth/me');
    }

    /**
     * RP-initiated OIDC logout — returns URL to redirect the browser to Authentik end_session_endpoint.
     * @return array
     */
    public function logout(): array
    {
        $response = $this->request('post', '/v1/auth/logout');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Get current user (claims from OIDC ID token + DB state).
     * @return array
     */
    public function me(): array
    {
        $response = $this->request('get', '/v1/auth/me');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Rotate our access+refresh JWT pair.
     * @param array $body
     * @return array
     */
    public function refresh(array $body): array
    {
        $response = $this->request('post', '/v1/auth/refresh', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Update current user locale (name/email come from OIDC ID token).
     * @param array $body
     * @return array
     */
    public function updateMe(array $body): array
    {
        $response = $this->request('patch', '/v1/auth/me', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Create Stripe Checkout session.
     * @param array $query
     * @return array
     */
    public function checkout(array $query = []): array
    {
        $response = $this->request('post', '/v1/billing/checkout', [
            'query' => $query,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * List plans (Free/Starter/Pro/Business).
     * @return array
     */
    public function getPlan(): array
    {
        $response = $this->request('get', '/v1/billing/plan');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Current usage vs plan limits (daily/weekly/monthly).
     * @return array
     */
    public function getUsage(): array
    {
        $response = $this->request('get', '/v1/billing/usage');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Create Stripe Customer Portal session.
     * @return array
     */
    public function portal(): array
    {
        $response = $this->request('post', '/v1/billing/portal');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Stripe webhook (verify HMAC SHA-256).
     * @param array $body
     * @return array
     */
    public function webhook(array $body): array
    {
        $response = $this->request('post', '/v1/billing/webhook', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * LLM autocomplete for partial question.
     * @param array $body
     * @param string $connector_id
     * @return array
     */
    public function autocomplete(array $body, string $connector_id): array
    {
        $response = $this->request('post', '/v1/connectors/' . $connector_id . '/autocomplete', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Create schema-only connector.
     * @param array $body
     * @return array
     */
    public function createConnector(array $body): array
    {
        $response = $this->request('post', '/v1/connectors', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete connector.
     * @param string $connector_id
     * @return void
     */
    public function deleteConnector(string $connector_id): void
    {
        $response = $this->request('delete', '/v1/connectors/' . $connector_id);
    }

    /**
     * Get connector.
     * @param string $connector_id
     * @return array
     */
    public function getConnector(string $connector_id): array
    {
        $response = $this->request('get', '/v1/connectors/' . $connector_id);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Get cached schema.
     * @param string $connector_id
     * @return array
     */
    public function getConnectorSchema(string $connector_id): array
    {
        $response = $this->request('get', '/v1/connectors/' . $connector_id . '/schema');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * LLM-generated Portuguese business questions.
     * @param string $connector_id
     * @return array
     */
    public function getSuggestions(string $connector_id): array
    {
        $response = $this->request('get', '/v1/connectors/' . $connector_id . '/suggestions');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * List connectors.
     * @return array
     */
    public function listConnectors(): array
    {
        $response = $this->request('get', '/v1/connectors');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Push schema from client (refresh).
     * @param array $body
     * @param string $connector_id
     * @return array
     */
    public function syncConnector(array $body, string $connector_id): array
    {
        $response = $this->request('post', '/v1/connectors/' . $connector_id . '/sync', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Update connector.
     * @param array $body
     * @param string $connector_id
     * @return array
     */
    public function updateConnector(array $body, string $connector_id): array
    {
        $response = $this->request('patch', '/v1/connectors/' . $connector_id, [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Dashboard stats (connectors, queries, top usage).
     * @return array
     */
    public function dashboardStats(): array
    {
        $response = $this->request('get', '/v1/dashboard/stats');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete feedback for a query.
     * @param string $query_id
     * @return void
     */
    public function deleteFeedback(string $query_id): void
    {
        $response = $this->request('delete', '/v1/feedbacks/' . $query_id);
    }

    /**
     * Get feedback for a query.
     * @param string $query_id
     * @return array
     */
    public function getFeedback(string $query_id): array
    {
        $response = $this->request('get', '/v1/feedbacks/' . $query_id);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Upsert feedback for a query.
     * @param array $body
     * @param string $query_id
     * @return array
     */
    public function upsertFeedback(array $body, string $query_id): array
    {
        $response = $this->request('put', '/v1/feedbacks/' . $query_id, [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Health check (versioned).
     * @return array
     */
    public function health(): array
    {
        $response = $this->request('get', '/v1/health');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Health check (legacy).
     * @return array
     */
    public function healthHealth(): array
    {
        $response = $this->request('get', '/health');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Return rendered HTML for an email template. Dev-only (404 in production)..
     * @param array $query
     * @return array
     */
    public function previewInternalEmail(array $query = []): array
    {
        $response = $this->request('get', '/v1/internal/email/preview', [
            'query' => $query,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Render or send an email template via Resend. Dev-only (404 in production)..
     * @param array $body
     * @param string $preview
     * @return array
     */
    public function testInternalEmail(array $body, string $preview = ''): array
    {
        $response = $this->request('post', '/v1/internal/email/test', [
            'json' => $body,
            'query' => ['preview' => $preview],
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * OIDC redirect_uri — exchanges code for tokens, provisions user, sets cookie, redirects to /auth/complete.
     * @param array $query
     * @return array
     */
    public function oidcCallback(array $query = []): array
    {
        $response = $this->request('get', '/v1/auth/oidc/callback', [
            'query' => $query,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Frontend calls this on /auth/complete to read the one-shot cookie and get tokens.
     * @param array $body
     * @return array
     */
    public function oidcComplete(array $body): array
    {
        $response = $this->request('post', '/v1/auth/oidc/complete', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Begin OIDC Authorization Code + PKCE flow (302 to Authentik).
     * @return array
     */
    public function oidcStart(): array
    {
        $response = $this->request('get', '/v1/auth/oidc/start');
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * WP plugin submits locally-executed result (API key only).
     * @param array $body
     * @param string $query_id
     * @return array
     */
    public function answerQuery(array $body, string $query_id): array
    {
        $response = $this->request('post', '/v1/queries/' . $query_id . '/answer', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Ask question (generate SQL only — client executes).
     * @param array $body
     * @return array
     */
    public function createQuery(array $body): array
    {
        $response = $this->request('post', '/v1/queries', [
            'json' => $body,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Get query detail (poll this to wait for status=ready).
     * @param string $query_id
     * @return array
     */
    public function getQuery(string $query_id): array
    {
        $response = $this->request('get', '/v1/queries/' . $query_id);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * Paginated query history.
     * @param array $query
     * @return array
     */
    public function listQueries(array $query = []): array
    {
        $response = $this->request('get', '/v1/queries', [
            'query' => $query,
        ]);
        return (array) json_decode((string) $response->getBody(), true);
    }

    /**
     * SSE stream — emits QueryResponse every 500ms until ready/failed or 60s timeout.
     * @param string $query_id
     * @return array
     */
    public function streamQuery(string $query_id): array
    {
        $response = $this->request('get', '/v1/queries/' . $query_id . '/stream');
        return (array) json_decode((string) $response->getBody(), true);
    }
}
