<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class AnalyticsQueryEvent
{
    public string $timestamp;
    public string $operation;
    public string $question;
    public string $sql;
    public string $status;
    public string $error_code;
    public int $total_tokens;
    public int $latency_ms;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->timestamp = (string) ($data['timestamp'] ?? '');
        $instance->operation = (string) ($data['operation'] ?? '');
        $instance->question = (string) ($data['question'] ?? '');
        $instance->sql = (string) ($data['sql'] ?? '');
        $instance->status = (string) ($data['status'] ?? '');
        $instance->error_code = (string) ($data['error_code'] ?? '');
        $instance->total_tokens = (int) ($data['total_tokens'] ?? 0);
        $instance->latency_ms = (int) ($data['latency_ms'] ?? 0);
        return $instance;
    }
}
