<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class AnalyticsQueriesResponse
{
    public string $items;
    public int $count;
    public int $days;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->items = (string) ($data['items'] ?? []);
        $instance->count = (int) ($data['count'] ?? 0);
        $instance->days = (int) ($data['days'] ?? 0);
        return $instance;
    }
}
