<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class ChangePlanResponse
{
    public string $plan_id;
    public string $interval;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->plan_id = (string) ($data['plan_id'] ?? '');
        $instance->interval = (string) ($data['interval'] ?? '');
        return $instance;
    }
}
