<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class ConnectorSyncRequest
{
    public string $schema;
    public ?string $db_version;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->schema = (string) ($data['schema'] ?? []);
        $instance->db_version = (string) ($data['db_version'] ?? '');
        return $instance;
    }
}
