<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class ConnectorResponse
{
    public string $id;
    public string $type;
    public string $name;
    public string $last_sync_at;
    public string $created_at;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->id = (string) ($data['id'] ?? '');
        $instance->type = (string) ($data['type'] ?? '');
        $instance->name = (string) ($data['name'] ?? '');
        $instance->last_sync_at = (string) ($data['last_sync_at'] ?? '');
        $instance->created_at = (string) ($data['created_at'] ?? '');
        return $instance;
    }
}
