<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class FeedbackCreate
{
    public bool $positive;
    public ?string $comment;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->positive = (bool) ($data['positive'] ?? false);
        $instance->comment = (string) ($data['comment'] ?? '');
        return $instance;
    }
}
