<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class HistoryPage
{
    public string $items;
    public string $next_cursor;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->items = (string) ($data['items'] ?? []);
        $instance->next_cursor = (string) ($data['next_cursor'] ?? '');
        return $instance;
    }
}
