<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class Integration
{
    public string $id;
    public string $type;
    public string $name;
    public ?string $description;
    public ?string $logo;
    public ?string $docs_url;
    public string $status;
    public ?string $engine;
    public ?int $default_port;
    public ?string $capabilities;
    public ?string $host;
    public ?string $connectors;
    public ?string $install_url;
    public ?string $package;
    public ?string $install_command;
    public ?string $os;
    public ?string $access;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->id = (string) ($data['id'] ?? '');
        $instance->type = (string) ($data['type'] ?? '');
        $instance->name = (string) ($data['name'] ?? '');
        $instance->description = (string) ($data['description'] ?? '');
        $instance->logo = (string) ($data['logo'] ?? '');
        $instance->docs_url = (string) ($data['docs_url'] ?? '');
        $instance->status = (string) ($data['status'] ?? '');
        $instance->engine = (string) ($data['engine'] ?? '');
        $instance->default_port = (int) ($data['default_port'] ?? 0);
        $instance->capabilities = (string) ($data['capabilities'] ?? []);
        $instance->host = (string) ($data['host'] ?? '');
        $instance->connectors = (string) ($data['connectors'] ?? []);
        $instance->install_url = (string) ($data['install_url'] ?? '');
        $instance->package = (string) ($data['package'] ?? '');
        $instance->install_command = (string) ($data['install_command'] ?? '');
        $instance->os = (string) ($data['os'] ?? []);
        $instance->access = (string) ($data['access'] ?? '');
        return $instance;
    }
}
