<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class Invoice
{
    public string $id;
    public string $number;
    public string $status;
    public int $amount;
    public string $currency;
    public string $created;
    public string $hosted_invoice_url;
    public string $invoice_pdf;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->id = (string) ($data['id'] ?? '');
        $instance->number = (string) ($data['number'] ?? '');
        $instance->status = (string) ($data['status'] ?? '');
        $instance->amount = (int) ($data['amount'] ?? 0);
        $instance->currency = (string) ($data['currency'] ?? '');
        $instance->created = (string) ($data['created'] ?? '');
        $instance->hosted_invoice_url = (string) ($data['hosted_invoice_url'] ?? '');
        $instance->invoice_pdf = (string) ($data['invoice_pdf'] ?? '');
        return $instance;
    }
}
