<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class LocalResultRequest
{
    public string $result_data;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->result_data = (string) ($data['result_data'] ?? []);
        return $instance;
    }
}
