<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class PaymentMethod
{
    public string $brand;
    public string $last4;
    public int $exp_month;
    public int $exp_year;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->brand = (string) ($data['brand'] ?? '');
        $instance->last4 = (string) ($data['last4'] ?? '');
        $instance->exp_month = (int) ($data['exp_month'] ?? 0);
        $instance->exp_year = (int) ($data['exp_year'] ?? 0);
        return $instance;
    }
}
