<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class PlanResponse
{
    public string $id;
    public string $name;
    public int $price;
    public int $price_annual;
    public int $credits_5h;
    public int $credits_7d;
    public string $support_tier;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->id = (string) ($data['id'] ?? '');
        $instance->name = (string) ($data['name'] ?? '');
        $instance->price = (int) ($data['price'] ?? 0);
        $instance->price_annual = (int) ($data['price_annual'] ?? 0);
        $instance->credits_5h = (int) ($data['credits_5h'] ?? 0);
        $instance->credits_7d = (int) ($data['credits_7d'] ?? 0);
        $instance->support_tier = (string) ($data['support_tier'] ?? '');
        return $instance;
    }
}
