<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class QueryRequest
{
    public string $connector_id;
    public string $question;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->connector_id = (string) ($data['connector_id'] ?? '');
        $instance->question = (string) ($data['question'] ?? '');
        return $instance;
    }
}
