<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class SubscriptionStateResponse
{
    public bool $cancel_at_period_end;
    public ?string $current_period_end;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->cancel_at_period_end = (bool) ($data['cancel_at_period_end'] ?? false);
        $instance->current_period_end = (string) ($data['current_period_end'] ?? '');
        return $instance;
    }
}
