<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class SubscriptionDetails
{
    public string $plan_id;
    public string $plan_name;
    public string $status;
    public string $current_period_start;
    public string $current_period_end;
    public bool $cancel_at_period_end;
    public string $interval;
    public int $amount;
    public string $currency;
    public string $scheduled_plan;
    public string $scheduled_change_at;
    public string $payment_method;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->plan_id = (string) ($data['plan_id'] ?? '');
        $instance->plan_name = (string) ($data['plan_name'] ?? '');
        $instance->status = (string) ($data['status'] ?? '');
        $instance->current_period_start = (string) ($data['current_period_start'] ?? '');
        $instance->current_period_end = (string) ($data['current_period_end'] ?? '');
        $instance->cancel_at_period_end = (bool) ($data['cancel_at_period_end'] ?? false);
        $instance->interval = (string) ($data['interval'] ?? '');
        $instance->amount = (int) ($data['amount'] ?? 0);
        $instance->currency = (string) ($data['currency'] ?? '');
        $instance->scheduled_plan = (string) ($data['scheduled_plan'] ?? '');
        $instance->scheduled_change_at = (string) ($data['scheduled_change_at'] ?? '');
        $instance->payment_method = (string) ($data['payment_method'] ?? '');
        return $instance;
    }
}
