<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class TableSchema
{
    public string $name;
    public string $columns;
    public ?int $rows_approx;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->name = (string) ($data['name'] ?? '');
        $instance->columns = (string) ($data['columns'] ?? []);
        $instance->rows_approx = (int) ($data['rows_approx'] ?? 0);
        return $instance;
    }
}
