<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class TokenResponse
{
    public string $access_token;
    public string $refresh_token;
    public string $token_type;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->access_token = (string) ($data['access_token'] ?? '');
        $instance->refresh_token = (string) ($data['refresh_token'] ?? '');
        $instance->token_type = (string) ($data['token_type'] ?? '');
        return $instance;
    }
}
