<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class UsageWindow
{
    public string $kind;
    public int $used_pct;
    public int $remaining_pct;
    public string $window_start;
    public string $window_end;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->kind = (string) ($data['kind'] ?? '');
        $instance->used_pct = (int) ($data['used_pct'] ?? 0);
        $instance->remaining_pct = (int) ($data['remaining_pct'] ?? 0);
        $instance->window_start = (string) ($data['window_start'] ?? '');
        $instance->window_end = (string) ($data['window_end'] ?? '');
        return $instance;
    }
}
