<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class UsageBucket
{
    public int $used;
    public int $limit;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->used = (int) ($data['used'] ?? 0);
        $instance->limit = (int) ($data['limit'] ?? 0);
        return $instance;
    }
}
