<?php

declare(strict_types=1);

/**
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec — do not edit.
 * Regenerate with: make generate
 */

namespace Clearsoft\EasySQL\Client\Models;

class UserResponse
{
    public string $id;
    public string $email;
    public string $name;
    public string $locale;
    public bool $email_verified;
    public ?string $email_verified_at;
    public string $created_at;

    /**
     * @param array $data Raw API response data.
     */
    public static function fromArray(array $data): self
    {
        $instance = new self();
        $instance->id = (string) ($data['id'] ?? '');
        $instance->email = (string) ($data['email'] ?? '');
        $instance->name = (string) ($data['name'] ?? '');
        $instance->locale = (string) ($data['locale'] ?? '');
        $instance->email_verified = (bool) ($data['email_verified'] ?? false);
        $instance->email_verified_at = (string) ($data['email_verified_at'] ?? '');
        $instance->created_at = (string) ($data['created_at'] ?? '');
        return $instance;
    }
}
