<?php

declare(strict_types=1);

/**
 * EasySQL API Client — auto-generated.
 *
 * 🤖 Generated by scripts/generate.php from the OpenAPI spec.
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY — regeneration overwrites it.
 * Regenerate with: make generate (EASYSQL_API_URL defaults to https://api.easysql.net)
 */

namespace Clearsoft\EasySQL\Client;

use GuzzleHttp\Client as GuzzleClient;
use Psr\Http\Message\ResponseInterface;
use Clearsoft\EasySQL\Client\Exceptions\ApiException;
use Clearsoft\EasySQL\Client\Http\TokenManager;
use Clearsoft\EasySQL\Client\Http\TokenStoreInterface;

class Client
{
    private GuzzleClient $http;
    private ?TokenManager $tokens = null;

    public function __construct(array $config = [])
    {
        // Full HTTP client injection (tests, custom transports). Token helpers
        // become no-ops in this mode — the caller owns the client.
        if (isset($config['http_client']) && $config['http_client'] instanceof GuzzleClient) {
            $this->http = $config['http_client'];
            return;
        }

        $baseUrl = rtrim($config['base_url'] ?? 'https://api.easysql.net', '/');

        $this->tokens = new TokenManager(
            $baseUrl,
            $config['access_token'] ?? null,
            $config['refresh_token'] ?? null,
            $config['handler'] ?? null,
        );

        $this->http = new GuzzleClient([
            'handler'     => $this->tokens->buildStack(),
            'base_uri'    => $baseUrl,
            'timeout'     => $config['timeout'] ?? 30.0,
            'http_errors' => false,
            'headers'     => [
                'Accept'       => 'application/json',
                'Content-Type' => 'application/json',
            ],
        ]);
    }

    /**
     * Set the Bearer token for authenticated requests.
     *
     * The underlying HTTP client is not recreated — the token is applied by
     * the handler stack on the next request.
     */
    public function setAccessToken(string $token): void
    {
        $this->tokens?->setAccessToken($token);
    }

    /**
     * Register a token store. When set, the client refreshes the access token
     * automatically (once) on a 401 response and persists the new tokens.
     */
    public function setTokenStore(TokenStoreInterface $store): void
    {
        $this->tokens?->setTokenStore($store);
    }

    /**
     * Get the underlying Guzzle client for custom requests.
     */
    public function getHttpClient(): GuzzleClient
    {
        return $this->http;
    }

    // ── Internal request helper ───────────────────────────────

    private function request(string $method, string $path, array $options = []): ResponseInterface
    {
        $response = $this->http->request($method, $path, $options);
        $statusCode = $response->getStatusCode();
        if ($statusCode >= 400) {
            throw ApiException::fromResponse($response);
        }
        return $response;
    }

    // ── Generated API methods ────────────────────────────────

{{IMPLEMENTATION}}
}
