<?php

/**
 * EasySQL API Client — auto-generated.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY.
 * It is regenerated by scripts/generate.php from the OpenAPI spec.
 */

namespace Clearsoft\EasySQL\SDK;

use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Exception\GuzzleException;
use Psr\Http\Message\ResponseInterface;
use Clearsoft\EasySQL\SDK\Exceptions\ApiException;

class Client
{
    private GuzzleClient $http;

    public function __construct(array $config = [])
    {
        if (isset($config['http_client']) && $config['http_client'] instanceof GuzzleClient) {
            $this->http = $config['http_client'];
        } else {
            $baseUrl = rtrim($config['base_url'] ?? 'https://api.easysql.net', '/');

            $this->http = new GuzzleClient([
                'base_uri' => $baseUrl,
                'timeout'  => $config['timeout'] ?? 30.0,
                'http_errors' => false,
                'headers' => [
                    'Accept'       => 'application/json',
                    'Content-Type' => 'application/json',
                ],
            ]);

            // If access token provided, attach Bearer header
            if (!empty($config['access_token'])) {
                $this->setAccessToken($config['access_token']);
            }
        }
    }

    /**
     * Set the Bearer token for authenticated requests.
     */
    public function setAccessToken(string $token): void
    {
        $this->http = new GuzzleClient([
            'base_uri'    => $this->http->getConfig('base_uri'),
            'timeout'     => $this->http->getConfig('timeout'),
            'http_errors' => false,
            'headers'     => [
                'Accept'        => 'application/json',
                'Content-Type'  => 'application/json',
                'Authorization' => "Bearer {$token}",
            ],
        ]);
    }

    /**
     * Get the underlying Guzzle client for custom requests.
     */
    public function getHttpClient(): GuzzleClient
    {
        return $this->http;
    }

    // ── Internal request helper ───────────────────────────────

    private function request(string $method, string $path, array $options = []): ResponseInterface
    {
        $response = $this->http->request($method, $path, $options);
        $statusCode = $response->getStatusCode();
        if ($statusCode >= 400) {
            throw ApiException::fromResponse($response);
        }
        return $response;
    }

    // ── Generated API methods ────────────────────────────────

{{IMPLEMENTATION}}
}
