<?php

/**
 * EasySQL API Client — auto-generated.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY.
 * It is regenerated by scripts/generate.php from the OpenAPI spec.
 */

namespace Clearsoft\EasySQL\SDK;

use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Exception\GuzzleException;
use Psr\Http\Message\ResponseInterface;
use Clearsoft\EasySQL\SDK\Exceptions\ApiException;

class Client
{
    private GuzzleClient $http;

    public function __construct(array $config = [])
    {
        if (isset($config['http_client']) && $config['http_client'] instanceof GuzzleClient) {
            $this->http = $config['http_client'];
        } else {
            $baseUrl = rtrim($config['base_url'] ?? 'https://api.easysql.net', '/');

            $this->http = new GuzzleClient([
                'base_uri' => $baseUrl,
                'timeout'  => $config['timeout'] ?? 30.0,
                'http_errors' => false,
                'headers' => [
                    'Accept'       => 'application/json',
                    'Content-Type' => 'application/json',
                ],
            ]);

            // If access token provided, attach Bearer header
            if (!empty($config['access_token'])) {
                $this->setAccessToken($config['access_token']);
            }
        }
    }

    /**
     * Set the Bearer token for authenticated requests.
     */
    public function setAccessToken(string $token): void
    {
        $this->http = new GuzzleClient([
            'base_uri'    => $this->http->getConfig('base_uri'),
            'timeout'     => $this->http->getConfig('timeout'),
            'http_errors' => false,
            'headers'     => [
                'Accept'        => 'application/json',
                'Content-Type'  => 'application/json',
                'Authorization' => "Bearer {$token}",
            ],
        ]);
    }

    /**
     * Get the underlying Guzzle client for custom requests.
     */
    public function getHttpClient(): GuzzleClient
    {
        return $this->http;
    }

    // ── Internal request helper ───────────────────────────────

    private function request(string $method, string $path, array $options = []): ResponseInterface
    {
        $response = $this->http->request($method, $path, $options);
        $statusCode = $response->getStatusCode();
        if ($statusCode >= 400) {
            throw ApiException::fromResponse($response);
        }
        return $response;
    }

    // ── Generated API methods ────────────────────────────────

    /**
     * Create Api Key.
     * @param array $body
     * @return array
     */
    public function createApiKey(array $body): array
    {
        $response = $this->request('post', '/v1/api-keys', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete Api Key.
     * @param string $key_id
     * @return void
     */
    public function deleteApiKey(string $key_id): void
    {
        $response = $this->request('delete', '/v1/api-keys/' . $key_id);
    }

    /**
     * List Api Keys.
     * @return array
     */
    public function listApiKeys(): array
    {
        $response = $this->request('get', '/v1/api-keys');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Change Password.
     * @param array $body
     * @return array
     */
    public function changePassword(array $body): array
    {
        $response = $this->request('post', '/v1/auth/change-password', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete Me.
     * @return void
     */
    public function deleteMe(): void
    {
        $response = $this->request('delete', '/v1/auth/me');
    }

    /**
     * Login.
     * @param array $body
     * @return array
     */
    public function login(array $body): array
    {
        $response = $this->request('post', '/v1/auth/login', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Me.
     * @return array
     */
    public function me(): array
    {
        $response = $this->request('get', '/v1/auth/me');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Refresh.
     * @param array $body
     * @return array
     */
    public function refresh(array $body): array
    {
        $response = $this->request('post', '/v1/auth/refresh', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Register.
     * @param array $body
     * @return array
     */
    public function register(array $body): array
    {
        $response = $this->request('post', '/v1/auth/register', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Update Me.
     * @param array $body
     * @return array
     */
    public function updateMe(array $body): array
    {
        $response = $this->request('patch', '/v1/auth/me', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Checkout.
     * @param string $price_id
     * @return array
     */
    public function checkout(array $query = []): array
    {
        $response = $this->request('post', '/v1/billing/checkout', [
            'query' => $query,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get Plan.
     * @return array
     */
    public function getPlan(): array
    {
        $response = $this->request('get', '/v1/billing/plan');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Portal.
     * @return array
     */
    public function portal(): array
    {
        $response = $this->request('post', '/v1/billing/portal');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Autocomplete.
     * @param string $connector_id
     * @param array $body
     * @return array
     */
    public function autocomplete(array $body, string $connector_id): array
    {
        $response = $this->request('post', '/v1/connectors/' . $connector_id . '/autocomplete', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Create Connector.
     * @param array $body
     * @return array
     */
    public function createConnector(array $body): array
    {
        $response = $this->request('post', '/v1/connectors', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete Connector.
     * @param string $connector_id
     * @return void
     */
    public function deleteConnector(string $connector_id): void
    {
        $response = $this->request('delete', '/v1/connectors/' . $connector_id);
    }

    /**
     * Get Connector.
     * @param string $connector_id
     * @return array
     */
    public function getConnector(string $connector_id): array
    {
        $response = $this->request('get', '/v1/connectors/' . $connector_id);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get Connector Schema.
     * @param string $connector_id
     * @return array
     */
    public function getConnectorSchema(string $connector_id): array
    {
        $response = $this->request('get', '/v1/connectors/' . $connector_id . '/schema');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get Suggestions.
     * @param string $connector_id
     * @return array
     */
    public function getSuggestions(string $connector_id): array
    {
        $response = $this->request('get', '/v1/connectors/' . $connector_id . '/suggestions');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * List Connectors.
     * @return array
     */
    public function listConnectors(): array
    {
        $response = $this->request('get', '/v1/connectors');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Sync Connector.
     * @param string $connector_id
     * @return array
     */
    public function syncConnector(string $connector_id): array
    {
        $response = $this->request('post', '/v1/connectors/' . $connector_id . '/sync');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Test Connector.
     * @param array $body
     * @return array
     */
    public function testConnector(array $body): array
    {
        $response = $this->request('post', '/v1/connectors/test', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Update Connector.
     * @param string $connector_id
     * @param array $body
     * @return array
     */
    public function updateConnector(array $body, string $connector_id): array
    {
        $response = $this->request('patch', '/v1/connectors/' . $connector_id, [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Dashboard Stats.
     * @return array
     */
    public function dashboardStats(): array
    {
        $response = $this->request('get', '/v1/dashboard/stats');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Health V1.
     * @return array
     */
    public function health(): array
    {
        $response = $this->request('get', '/v1/health');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Health.
     * @return array
     */
    public function healthHealth(): array
    {
        $response = $this->request('get', '/health');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete Feedback.
     * @param string $query_id
     * @return void
     */
    public function deleteFeedback(string $query_id): void
    {
        $response = $this->request('delete', '/v1/feedbacks/' . $query_id);
    }

    /**
     * Get Feedback.
     * @param string $query_id
     * @return array
     */
    public function getFeedback(string $query_id): array
    {
        $response = $this->request('get', '/v1/feedbacks/' . $query_id);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Upsert Feedback.
     * @param string $query_id
     * @param array $body
     * @return array
     */
    public function upsertFeedback(array $body, string $query_id): array
    {
        $response = $this->request('put', '/v1/feedbacks/' . $query_id, [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Create Query.
     * @param array $body
     * @return array
     */
    public function createQuery(array $body): array
    {
        $response = $this->request('post', '/v1/queries', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get Query.
     * @param string $query_id
     * @return array
     */
    public function getQuery(string $query_id): array
    {
        $response = $this->request('get', '/v1/queries/' . $query_id);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * List Queries.
     * @param int|null $page
     * @param int|null $per_page
     * @return array
     */
    public function listQueries(array $query = []): array
    {
        $response = $this->request('get', '/v1/queries', [
            'query' => $query,
        ]);
        return json_decode((string) $response->getBody(), true);
    }
}
