<?php

/**
 * EasySQL API Client — auto-generated.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY.
 * It is regenerated by scripts/generate.php from the OpenAPI spec.
 */

namespace Clearsoft\EasySQL\SDK;

use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Exception\GuzzleException;
use Psr\Http\Message\ResponseInterface;
use Clearsoft\EasySQL\SDK\Exceptions\ApiException;

class Client
{
    private GuzzleClient $http;

    public function __construct(array $config = [])
    {
        if (isset($config['http_client']) && $config['http_client'] instanceof GuzzleClient) {
            $this->http = $config['http_client'];
        } else {
            $baseUrl = rtrim($config['base_url'] ?? 'https://api.easysql.net', '/');

            $this->http = new GuzzleClient([
                'base_uri' => $baseUrl,
                'timeout'  => $config['timeout'] ?? 30.0,
                'http_errors' => false,
                'headers' => [
                    'Accept'       => 'application/json',
                    'Content-Type' => 'application/json',
                ],
            ]);

            // If access token provided, attach Bearer header
            if (!empty($config['access_token'])) {
                $this->setAccessToken($config['access_token']);
            }
        }
    }

    /**
     * Set the Bearer token for authenticated requests.
     */
    public function setAccessToken(string $token): void
    {
        $this->http = new GuzzleClient([
            'base_uri'    => $this->http->getConfig('base_uri'),
            'timeout'     => $this->http->getConfig('timeout'),
            'http_errors' => false,
            'headers'     => [
                'Accept'        => 'application/json',
                'Content-Type'  => 'application/json',
                'Authorization' => "Bearer {$token}",
            ],
        ]);
    }

    /**
     * Get the underlying Guzzle client for custom requests.
     */
    public function getHttpClient(): GuzzleClient
    {
        return $this->http;
    }

    // ── Internal request helper ───────────────────────────────

    private function request(string $method, string $path, array $options = []): ResponseInterface
    {
        $response = $this->http->request($method, $path, $options);
        $statusCode = $response->getStatusCode();
        if ($statusCode >= 400) {
            throw ApiException::fromResponse($response);
        }
        return $response;
    }

    // ── Generated API methods ────────────────────────────────

    /**
     * Create API key (returns full key once).
     * @param array $body
     * @return array
     */
    public function createApiKey(array $body): array
    {
        $response = $this->request('post', '/v1/api-keys', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Revoke API key (soft delete).
     * @param string $key_id
     * @return void
     */
    public function deleteApiKey(string $key_id): void
    {
        $response = $this->request('delete', '/v1/api-keys/' . $key_id);
    }

    /**
     * List API keys (without secret).
     * @return array
     */
    public function listApiKeys(): array
    {
        $response = $this->request('get', '/v1/api-keys');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete current user (hard delete).
     * @return void
     */
    public function deleteMe(): void
    {
        $response = $this->request('delete', '/v1/auth/me');
    }

    /**
     * RP-initiated OIDC logout — returns URL to redirect the browser to Authentik end_session_endpoint.
     * @return array
     */
    public function logout(): array
    {
        $response = $this->request('post', '/v1/auth/logout');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get current user (claims from OIDC ID token + DB state).
     * @return array
     */
    public function me(): array
    {
        $response = $this->request('get', '/v1/auth/me');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Rotate our access+refresh JWT pair.
     * @param array $body
     * @return array
     */
    public function refresh(array $body): array
    {
        $response = $this->request('post', '/v1/auth/refresh', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Update current user locale (name/email come from OIDC ID token).
     * @param array $body
     * @return array
     */
    public function updateMe(array $body): array
    {
        $response = $this->request('patch', '/v1/auth/me', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Create Stripe Checkout session.
     * @param string $price_id
     * @return array
     */
    public function checkout(array $query = []): array
    {
        $response = $this->request('post', '/v1/billing/checkout', [
            'query' => $query,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * List plans (Free/Starter/Pro/Business).
     * @return array
     */
    public function getPlan(): array
    {
        $response = $this->request('get', '/v1/billing/plan');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Create Stripe Customer Portal session.
     * @return array
     */
    public function portal(): array
    {
        $response = $this->request('post', '/v1/billing/portal');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Stripe webhook (verify HMAC SHA-256).
     * @return array
     */
    public function webhook(array $body): array
    {
        $response = $this->request('post', '/v1/billing/webhook', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * LLM autocomplete for partial question.
     * @param array $body
     * @return array
     */
    public function autocomplete(array $body): array
    {
        $response = $this->request('post', '/v1/connectors/' . '{connector_id}' . '/autocomplete', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Create schema-only connector.
     * @param array $body
     * @return array
     */
    public function createConnector(array $body): array
    {
        $response = $this->request('post', '/v1/connectors', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete connector.
     * @return void
     */
    public function deleteConnector(): void
    {
        $response = $this->request('delete', '/v1/connectors/' . '{connector_id}');
    }

    /**
     * Get connector.
     * @return array
     */
    public function getConnector(): array
    {
        $response = $this->request('get', '/v1/connectors/' . '{connector_id}');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get cached schema.
     * @return array
     */
    public function getConnectorSchema(): array
    {
        $response = $this->request('get', '/v1/connectors/' . '{connector_id}' . '/schema');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * LLM-generated Portuguese business questions.
     * @return array
     */
    public function getSuggestions(): array
    {
        $response = $this->request('get', '/v1/connectors/' . '{connector_id}' . '/suggestions');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * List connectors.
     * @return array
     */
    public function listConnectors(): array
    {
        $response = $this->request('get', '/v1/connectors');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Push schema from client (refresh).
     * @param array $body
     * @return array
     */
    public function syncConnector(array $body): array
    {
        $response = $this->request('post', '/v1/connectors/' . '{connector_id}' . '/sync', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Update connector.
     * @param array $body
     * @return array
     */
    public function updateConnector(array $body): array
    {
        $response = $this->request('patch', '/v1/connectors/' . '{connector_id}', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Dashboard stats (connectors, queries, top usage).
     * @return array
     */
    public function dashboardStats(): array
    {
        $response = $this->request('get', '/v1/dashboard/stats');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Delete feedback for a query.
     * @return void
     */
    public function deleteFeedback(): void
    {
        $response = $this->request('delete', '/v1/feedbacks/' . '{query_id}');
    }

    /**
     * Get feedback for a query.
     * @return array
     */
    public function getFeedback(): array
    {
        $response = $this->request('get', '/v1/feedbacks/' . '{query_id}');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Upsert feedback for a query.
     * @param array $body
     * @return array
     */
    public function upsertFeedback(array $body): array
    {
        $response = $this->request('put', '/v1/feedbacks/' . '{query_id}', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Health check (versioned).
     * @return array
     */
    public function health(): array
    {
        $response = $this->request('get', '/v1/health');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Health check (legacy).
     * @return array
     */
    public function healthHealth(): array
    {
        $response = $this->request('get', '/health');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Return rendered HTML for an email template. Dev-only (404 in production)..
     * @param string $template
     * @param string|null $name
     * @param string|null $to
     * @param string|null $token
     * @return array
     */
    public function previewInternalEmail(array $query = []): array
    {
        $response = $this->request('get', '/v1/internal/email/preview', [
            'query' => $query,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Render or send an email template via Resend. Dev-only (404 in production)..
     * @param string|null $preview
     * @return array
     */
    public function testInternalEmail(array $body, string $preview = ''): array
    {
        $response = $this->request('post', '/v1/internal/email/test', [
            'json' => $body,
            'query' => ['preview' => $preview],
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * OIDC redirect_uri — exchanges code for tokens, provisions user, sets cookie, redirects to /auth/complete.
     * @param string $code
     * @param string $state
     * @return array
     */
    public function oidcCallback(array $query = []): array
    {
        $response = $this->request('get', '/v1/auth/oidc/callback', [
            'query' => $query,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Frontend calls this on /auth/complete to read the one-shot cookie and get tokens.
     * @param array $body
     * @return array
     */
    public function oidcComplete(array $body): array
    {
        $response = $this->request('post', '/v1/auth/oidc/complete', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Begin OIDC Authorization Code + PKCE flow (302 to Authentik).
     * @return array
     */
    public function oidcStart(): array
    {
        $response = $this->request('get', '/v1/auth/oidc/start');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * WP plugin submits locally-executed result (API key only).
     * @param array $body
     * @return array
     */
    public function answerQuery(array $body): array
    {
        $response = $this->request('post', '/v1/queries/' . '{query_id}' . '/answer', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Ask question (generate SQL only — client executes).
     * @param array $body
     * @return array
     */
    public function createQuery(array $body): array
    {
        $response = $this->request('post', '/v1/queries', [
            'json' => $body,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Get query detail (poll this to wait for status=ready).
     * @return array
     */
    public function getQuery(): array
    {
        $response = $this->request('get', '/v1/queries/' . '{query_id}');
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Paginated query history.
     * @param int|null $page
     * @param int|null $per_page
     * @return array
     */
    public function listQueries(array $query = []): array
    {
        $response = $this->request('get', '/v1/queries', [
            'query' => $query,
        ]);
        return json_decode((string) $response->getBody(), true);
    }

    /**
     * SSE stream — emits QueryResponse every 500ms until ready/failed or 60s timeout.
     * @return array
     */
    public function streamQuery(): array
    {
        $response = $this->request('get', '/v1/queries/' . '{query_id}' . '/stream');
        return json_decode((string) $response->getBody(), true);
    }
}
